SQS -> Pulsar topic routing enhancement
streamnative/pulsar-io-sqs pull request #165
Opened 2021-10-05 21:48 UTC by seburke

Added functionality for routing to many topics based on a SQS message attribute

2021-10-08 09:41 UTC, freeznet commented on src/main/java/org/apache/pulsar/ecosystem/io/sqs/SQSRecord.java
> +            return Optional.of(msg.getMessageAttributes().get(SQSUtils.PULSAR_TOPIC_ATTRIBUTE).getStringValue());
Can we have some validation with the topic name?

2021-10-11 03:07 UTC, Anonymitaet commented
@freeznet thanks for your info. Now, @Huanli-Meng is the owner of connectors, she can help handle connector docs.

2021-11-02 17:44 UTC, seburke commented
Just circling back with this if there is anything else needed to get this merged. 
Thanks!

2021-11-05 05:12 UTC, freeznet approved these changes
LGTM

2021-11-05 05:13 UTC, freeznet commented
@nlu90 could you please help to review this PR when you have time, thanks.

2021-11-05 18:10 UTC, nlu90 requested changes
I'm a little concerned introducing the google guava and apache commons dependency for implementing one method.

Can we do it with the native java language features for now and avoid introducing such dependencies?

2021-11-09 19:29 UTC, seburke commented
> I'm a little concerned introducing the google guava and apache commons dependency for implementing one method.
> 
> Can we do it with the native java language features for now and avoid introducing such dependencies?

I removed the new dependencies as you mentioned. Getting rid of the checkArgument method was straightforward. The isNotBlank method is a little more complex and seems unnecessary to implement when the awssdk has the same method and the implementations are pretty much the same so I switched back to that import since it is already imported anyway. If you want something else, happy to go that route, this just seemed easiest and I was trying to copy what the full pulsar topic validation is as closely as possible.

2021-11-09 20:54 UTC, nlu90 approved these changes
LGTM

2021-11-09 20:55 UTC, nlu90 commented
> > I'm a little concerned introducing the google guava and apache commons dependency for implementing one method.
> > Can we do it with the native java language features for now and avoid introducing such dependencies?
> 
> I removed the new dependencies as you mentioned. Getting rid of the checkArgument method was straightforward. The isNotBlank method is a little more complex and seems unnecessary to implement when the awssdk has the same method and the implementations are pretty much the same so I switched back to that import since it is already imported anyway. If you want something else, happy to go that route, this just seemed easiest and I was trying to copy what the full pulsar topic validation is as closely as possible.

Thanks for your contribution!

2021-11-12 08:34 UTC, freeznet commented
@seburke would you please rebase the master so that the integration tests CI can be fixed, thanks.

2021-11-12 19:55 UTC, merged